services:
  apache:
    build: .
    restart: 'always'
    container_name: webServer
    ports:
      - '80:80'
    volumes:
      - "./public_html:/usr/local/apache2/htdocs/"
      - "./usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  mysql:
    image: mysql:8.0
    restart: always
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - apache
  phpmyadmin:
    image: arm64v8/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
    ports:
      - "3000:80"